// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/cloud/speech/v2/cloud_speech_minimal.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
    import FoundationEssentials
#else
    import Foundation
#endif
import SwiftProtobuf

/// If the compiler emits an error on this type, it is because this file
/// was generated by a version of the `protoc` Swift plug-in that is
/// incompatible with the version of SwiftProtobuf to which you are linking.
/// Please ensure that you are building against the same version of the API
/// that was used to generate this file.
private struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
    struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
    typealias Version = _2
}

struct Google_Cloud_Speech_V2_AutoDetectDecodingConfig: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
}

struct Google_Cloud_Speech_V2_ExplicitDecodingConfig: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var encoding: Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding = .unspecified

    var sampleRateHertz: Int32 = 0

    var audioChannelCount: Int32 = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum AudioEncoding: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case unspecified // = 0
        case linear16 // = 1
        case mulaw // = 2
        case alaw // = 3
        case UNRECOGNIZED(Int)

        init() {
            self = .unspecified
        }

        init?(rawValue: Int) {
            switch rawValue {
            case 0: self = .unspecified
            case 1: self = .linear16
            case 2: self = .mulaw
            case 3: self = .alaw
            default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
            case .unspecified: 0
            case .linear16: 1
            case .mulaw: 2
            case .alaw: 3
            case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding] = [
            .unspecified,
            .linear16,
            .mulaw,
            .alaw
        ]
    }
}

struct Google_Cloud_Speech_V2_RecognitionConfig: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var decodingConfig: Google_Cloud_Speech_V2_RecognitionConfig.OneOf_DecodingConfig?

    var autoDecodingConfig: Google_Cloud_Speech_V2_AutoDetectDecodingConfig {
        get {
            if case let .autoDecodingConfig(v)? = decodingConfig { return v }
            return Google_Cloud_Speech_V2_AutoDetectDecodingConfig()
        }
        set { decodingConfig = .autoDecodingConfig(newValue) }
    }

    var explicitDecodingConfig: Google_Cloud_Speech_V2_ExplicitDecodingConfig {
        get {
            if case let .explicitDecodingConfig(v)? = decodingConfig { return v }
            return Google_Cloud_Speech_V2_ExplicitDecodingConfig()
        }
        set { decodingConfig = .explicitDecodingConfig(newValue) }
    }

    var model: String = .init()

    var languageCodes: [String] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_DecodingConfig: Equatable, Sendable {
        case autoDecodingConfig(Google_Cloud_Speech_V2_AutoDetectDecodingConfig)
        case explicitDecodingConfig(Google_Cloud_Speech_V2_ExplicitDecodingConfig)
    }

    init() {}
}

struct Google_Cloud_Speech_V2_StreamingRecognitionFeatures: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var enableVoiceActivityEvents: Bool = false

    var interimResults: Bool = false

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Google_Cloud_Speech_V2_StreamingRecognitionConfig: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var config: Google_Cloud_Speech_V2_RecognitionConfig {
        get { _config ?? Google_Cloud_Speech_V2_RecognitionConfig() }
        set { _config = newValue }
    }

    /// Returns true if `config` has been explicitly set.
    var hasConfig: Bool {
        _config != nil
    }

    /// Clears the value of `config`. Subsequent reads from it will return its default value.
    mutating func clearConfig() {
        _config = nil
    }

    var streamingFeatures: Google_Cloud_Speech_V2_StreamingRecognitionFeatures {
        get { _streamingFeatures ?? Google_Cloud_Speech_V2_StreamingRecognitionFeatures() }
        set { _streamingFeatures = newValue }
    }

    /// Returns true if `streamingFeatures` has been explicitly set.
    var hasStreamingFeatures: Bool {
        _streamingFeatures != nil
    }

    /// Clears the value of `streamingFeatures`. Subsequent reads from it will return its default value.
    mutating func clearStreamingFeatures() {
        _streamingFeatures = nil
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _config: Google_Cloud_Speech_V2_RecognitionConfig?
    fileprivate var _streamingFeatures: Google_Cloud_Speech_V2_StreamingRecognitionFeatures?
}

struct Google_Cloud_Speech_V2_StreamingRecognizeRequest: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var recognizer: String = .init()

    var streamingRequest: Google_Cloud_Speech_V2_StreamingRecognizeRequest.OneOf_StreamingRequest?

    var streamingConfig: Google_Cloud_Speech_V2_StreamingRecognitionConfig {
        get {
            if case let .streamingConfig(v)? = streamingRequest { return v }
            return Google_Cloud_Speech_V2_StreamingRecognitionConfig()
        }
        set { streamingRequest = .streamingConfig(newValue) }
    }

    var audio: Data {
        get {
            if case let .audio(v)? = streamingRequest { return v }
            return Data()
        }
        set { streamingRequest = .audio(newValue) }
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_StreamingRequest: Equatable, Sendable {
        case streamingConfig(Google_Cloud_Speech_V2_StreamingRecognitionConfig)
        case audio(Data)
    }

    init() {}
}

struct Google_Cloud_Speech_V2_SpeechRecognitionAlternative: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var transcript: String = .init()

    var confidence: Float = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Google_Cloud_Speech_V2_StreamingRecognitionResult: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var alternatives: [Google_Cloud_Speech_V2_SpeechRecognitionAlternative] = []

    var isFinal: Bool = false

    var stability: Float = 0

    var channelTag: Int32 = 0

    var languageCode: String = .init()

    var unknownFields = SwiftProtobuf.UnknownStorage()
}

struct Google_Cloud_Speech_V2_StreamingRecognizeResponse: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var results: [Google_Cloud_Speech_V2_StreamingRecognitionResult] = []

    var speechEventType: Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType = .unspecified

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum SpeechEventType: SwiftProtobuf.Enum, Swift.CaseIterable {
        typealias RawValue = Int
        case unspecified // = 0
        case endOfSingleUtterance // = 1
        case speechActivityBegin // = 2
        case speechActivityEnd // = 3
        case UNRECOGNIZED(Int)

        init() {
            self = .unspecified
        }

        init?(rawValue: Int) {
            switch rawValue {
            case 0: self = .unspecified
            case 1: self = .endOfSingleUtterance
            case 2: self = .speechActivityBegin
            case 3: self = .speechActivityEnd
            default: self = .UNRECOGNIZED(rawValue)
            }
        }

        var rawValue: Int {
            switch self {
            case .unspecified: 0
            case .endOfSingleUtterance: 1
            case .speechActivityBegin: 2
            case .speechActivityEnd: 3
            case let .UNRECOGNIZED(i): i
            }
        }

        /// The compiler won't synthesize support with the UNRECOGNIZED case.
        static let allCases: [Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType] = [
            .unspecified,
            .endOfSingleUtterance,
            .speechActivityBegin,
            .speechActivityEnd
        ]
    }
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

private let _protobuf_package = "google.cloud.speech.v2"

extension Google_Cloud_Speech_V2_AutoDetectDecodingConfig: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".AutoDetectDecodingConfig"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap()

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        // Load everything into unknown fields
        while try decoder.nextFieldNumber() != nil {}
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_AutoDetectDecodingConfig,
        rhs: Google_Cloud_Speech_V2_AutoDetectDecodingConfig
    ) -> Bool {
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_ExplicitDecodingConfig: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".ExplicitDecodingConfig"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{1}encoding\0\u{3}sample_rate_hertz\0\u{3}audio_channel_count\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularEnumField(value: &encoding)
            case 2: try decoder.decodeSingularInt32Field(value: &sampleRateHertz)
            case 3: try decoder.decodeSingularInt32Field(value: &audioChannelCount)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if encoding != .unspecified {
            try visitor.visitSingularEnumField(value: encoding, fieldNumber: 1)
        }
        if sampleRateHertz != 0 {
            try visitor.visitSingularInt32Field(value: sampleRateHertz, fieldNumber: 2)
        }
        if audioChannelCount != 0 {
            try visitor.visitSingularInt32Field(value: audioChannelCount, fieldNumber: 3)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_ExplicitDecodingConfig,
        rhs: Google_Cloud_Speech_V2_ExplicitDecodingConfig
    ) -> Bool {
        if lhs.encoding != rhs.encoding { return false }
        if lhs.sampleRateHertz != rhs.sampleRateHertz { return false }
        if lhs.audioChannelCount != rhs.audioChannelCount { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_ExplicitDecodingConfig.AudioEncoding: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{2}\0AUDIO_ENCODING_UNSPECIFIED\0\u{1}LINEAR16\0\u{1}MULAW\0\u{1}ALAW\0")
}

extension Google_Cloud_Speech_V2_RecognitionConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase,
    SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".RecognitionConfig"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{4}\u{7}auto_decoding_config\0\u{3}explicit_decoding_config\0\u{1}model\0\u{3}language_codes\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 7: try {
                    var v: Google_Cloud_Speech_V2_AutoDetectDecodingConfig?
                    var hadOneofValue = false
                    if let current = self.decodingConfig {
                        hadOneofValue = true
                        if case let .autoDecodingConfig(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.decodingConfig = .autoDecodingConfig(v)
                    }
                }()
            case 8: try {
                    var v: Google_Cloud_Speech_V2_ExplicitDecodingConfig?
                    var hadOneofValue = false
                    if let current = self.decodingConfig {
                        hadOneofValue = true
                        if case let .explicitDecodingConfig(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.decodingConfig = .explicitDecodingConfig(v)
                    }
                }()
            case 9: try decoder.decodeSingularStringField(value: &model)
            case 10: try decoder.decodeRepeatedStringField(value: &languageCodes)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        switch decodingConfig {
        case .autoDecodingConfig?: try {
                guard case let .autoDecodingConfig(v)? = self.decodingConfig else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
            }()
        case .explicitDecodingConfig?: try {
                guard case let .explicitDecodingConfig(v)? = self.decodingConfig else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
            }()
        case nil: break
        }
        if !model.isEmpty {
            try visitor.visitSingularStringField(value: model, fieldNumber: 9)
        }
        if !languageCodes.isEmpty {
            try visitor.visitRepeatedStringField(value: languageCodes, fieldNumber: 10)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (lhs: Google_Cloud_Speech_V2_RecognitionConfig,
                    rhs: Google_Cloud_Speech_V2_RecognitionConfig) -> Bool {
        if lhs.decodingConfig != rhs.decodingConfig { return false }
        if lhs.model != rhs.model { return false }
        if lhs.languageCodes != rhs.languageCodes { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionFeatures: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionFeatures"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{3}enable_voice_activity_events\0\u{3}interim_results\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularBoolField(value: &enableVoiceActivityEvents)
            case 2: try decoder.decodeSingularBoolField(value: &interimResults)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if enableVoiceActivityEvents != false {
            try visitor.visitSingularBoolField(value: enableVoiceActivityEvents, fieldNumber: 1)
        }
        if interimResults != false {
            try visitor.visitSingularBoolField(value: interimResults, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_StreamingRecognitionFeatures,
        rhs: Google_Cloud_Speech_V2_StreamingRecognitionFeatures
    ) -> Bool {
        if lhs.enableVoiceActivityEvents != rhs.enableVoiceActivityEvents { return false }
        if lhs.interimResults != rhs.interimResults { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionConfig: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionConfig"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}config\0\u{3}streaming_features\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularMessageField(value: &_config)
            case 2: try decoder.decodeSingularMessageField(value: &_streamingFeatures)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if let v = _config {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
        }
        try { if let v = self._streamingFeatures {
            try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
        } }()
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_StreamingRecognitionConfig,
        rhs: Google_Cloud_Speech_V2_StreamingRecognitionConfig
    ) -> Bool {
        if lhs._config != rhs._config { return false }
        if lhs._streamingFeatures != rhs._streamingFeatures { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeRequest: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".StreamingRecognizeRequest"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{2}\u{3}recognizer\0\u{2}\u{2}audio\0\u{3}streaming_config\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 3: try decoder.decodeSingularStringField(value: &recognizer)
            case 5: try {
                    var v: Data?
                    try decoder.decodeSingularBytesField(value: &v)
                    if let v {
                        if self.streamingRequest != nil { try decoder.handleConflictingOneOf() }
                        self.streamingRequest = .audio(v)
                    }
                }()
            case 6: try {
                    var v: Google_Cloud_Speech_V2_StreamingRecognitionConfig?
                    var hadOneofValue = false
                    if let current = self.streamingRequest {
                        hadOneofValue = true
                        if case let .streamingConfig(m) = current { v = m }
                    }
                    try decoder.decodeSingularMessageField(value: &v)
                    if let v {
                        if hadOneofValue { try decoder.handleConflictingOneOf() }
                        self.streamingRequest = .streamingConfig(v)
                    }
                }()
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every if/case branch local when no optimizations
        // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
        // https://github.com/apple/swift-protobuf/issues/1182
        if !recognizer.isEmpty {
            try visitor.visitSingularStringField(value: recognizer, fieldNumber: 3)
        }
        switch streamingRequest {
        case .audio?: try {
                guard case let .audio(v)? = self.streamingRequest else { preconditionFailure() }
                try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
            }()
        case .streamingConfig?: try {
                guard case let .streamingConfig(v)? = self.streamingRequest else { preconditionFailure() }
                try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
            }()
        case nil: break
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_StreamingRecognizeRequest,
        rhs: Google_Cloud_Speech_V2_StreamingRecognizeRequest
    ) -> Bool {
        if lhs.recognizer != rhs.recognizer { return false }
        if lhs.streamingRequest != rhs.streamingRequest { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_SpeechRecognitionAlternative: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".SpeechRecognitionAlternative"
    static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}transcript\0\u{1}confidence\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeSingularStringField(value: &transcript)
            case 2: try decoder.decodeSingularFloatField(value: &confidence)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !transcript.isEmpty {
            try visitor.visitSingularStringField(value: transcript, fieldNumber: 1)
        }
        if confidence.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: confidence, fieldNumber: 2)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_SpeechRecognitionAlternative,
        rhs: Google_Cloud_Speech_V2_SpeechRecognitionAlternative
    ) -> Bool {
        if lhs.transcript != rhs.transcript { return false }
        if lhs.confidence != rhs.confidence { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognitionResult: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".StreamingRecognitionResult"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{1}alternatives\0\u{3}is_final\0\u{1}stability\0\u{4}\u{2}channel_tag\0\u{3}language_code\0"
        )

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 1: try decoder.decodeRepeatedMessageField(value: &alternatives)
            case 2: try decoder.decodeSingularBoolField(value: &isFinal)
            case 3: try decoder.decodeSingularFloatField(value: &stability)
            case 5: try decoder.decodeSingularInt32Field(value: &channelTag)
            case 6: try decoder.decodeSingularStringField(value: &languageCode)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if !alternatives.isEmpty {
            try visitor.visitRepeatedMessageField(value: alternatives, fieldNumber: 1)
        }
        if isFinal != false {
            try visitor.visitSingularBoolField(value: isFinal, fieldNumber: 2)
        }
        if stability.bitPattern != 0 {
            try visitor.visitSingularFloatField(value: stability, fieldNumber: 3)
        }
        if channelTag != 0 {
            try visitor.visitSingularInt32Field(value: channelTag, fieldNumber: 5)
        }
        if !languageCode.isEmpty {
            try visitor.visitSingularStringField(value: languageCode, fieldNumber: 6)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_StreamingRecognitionResult,
        rhs: Google_Cloud_Speech_V2_StreamingRecognitionResult
    ) -> Bool {
        if lhs.alternatives != rhs.alternatives { return false }
        if lhs.isFinal != rhs.isFinal { return false }
        if lhs.stability != rhs.stability { return false }
        if lhs.channelTag != rhs.channelTag { return false }
        if lhs.languageCode != rhs.languageCode { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeResponse: SwiftProtobuf.Message,
    SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
    static let protoMessageName: String = _protobuf_package + ".StreamingRecognizeResponse"
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(bytecode: "\0\u{4}\u{3}speech_event_type\0\u{2}\u{3}results\0")

    mutating func decodeMessage(decoder: inout some SwiftProtobuf.Decoder) throws {
        while let fieldNumber = try decoder.nextFieldNumber() {
            // The use of inline closures is to circumvent an issue where the compiler
            // allocates stack space for every case branch when no optimizations are
            // enabled. https://github.com/apple/swift-protobuf/issues/1034
            switch fieldNumber {
            case 3: try decoder.decodeSingularEnumField(value: &speechEventType)
            case 6: try decoder.decodeRepeatedMessageField(value: &results)
            default: break
            }
        }
    }

    func traverse(visitor: inout some SwiftProtobuf.Visitor) throws {
        if speechEventType != .unspecified {
            try visitor.visitSingularEnumField(value: speechEventType, fieldNumber: 3)
        }
        if !results.isEmpty {
            try visitor.visitRepeatedMessageField(value: results, fieldNumber: 6)
        }
        try unknownFields.traverse(visitor: &visitor)
    }

    static func == (
        lhs: Google_Cloud_Speech_V2_StreamingRecognizeResponse,
        rhs: Google_Cloud_Speech_V2_StreamingRecognizeResponse
    ) -> Bool {
        if lhs.results != rhs.results { return false }
        if lhs.speechEventType != rhs.speechEventType { return false }
        if lhs.unknownFields != rhs.unknownFields { return false }
        return true
    }
}

extension Google_Cloud_Speech_V2_StreamingRecognizeResponse.SpeechEventType: SwiftProtobuf._ProtoNameProviding {
    static let _protobuf_nameMap = SwiftProtobuf
        ._NameMap(
            bytecode: "\0\u{2}\0SPEECH_EVENT_TYPE_UNSPECIFIED\0\u{1}END_OF_SINGLE_UTTERANCE\0\u{1}SPEECH_ACTIVITY_BEGIN\0\u{1}SPEECH_ACTIVITY_END\0"
        )
}
